create table if not exists customer_class_chart_tree(
customer_class_id Integer not null,
tree_effective_date varchar(255) null,
tree_code Integer null,
tree_description varchar(255) null,
hierarchy1 varchar(255) null,
hierarchy1_desc varchar(255) null,
hierarchy2 varchar(255) null,
hierarchy2_desc varchar(255) null,
hierarchy3 varchar(255) null,
hierarchy3_desc varchar(255) null,
hierarchy4 varchar(255) null,
hierarchy4_desc varchar(255) null,
hierarchy5 varchar(255) null,
hierarchy5_desc varchar(255) null,
hierarchy6 varchar(255) null,
hierarchy6_desc varchar(255) null,
hierarchy7 varchar(255) null,
hierarchy7_desc varchar(255) null,
creation_date varchar(255) null,
modified_date varchar(255) null,
entity_state varchar(255) null,
constraint customer_class_chart_tree_pk primary key(customer_class_id));
